import java.text.SimpleDateFormat

apply plugin: 'com.android.library'

android {

    defaultConfig {
        minSdkVersion 24
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 28
        buildConfigField "String", "APP_BUILD_TIME", '"' + (new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ROOT).format(new Date())) + '"'
    }

    buildFeatures {
        buildConfig = true
    }

    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace = 'org.firstinspires.ftc.core'

}

repositories {
    mavenCentral()

    maven { url = 'https://maven.brott.dev/' }
    maven { url = 'https://mymaven.bylazar.com/releases' }
    maven { url = "https://repo.dairy.foundation/releases" }
    maven { url = "https://repo.dairy.foundation/snapshots" }
}


dependencies {
    implementation project(':FtcRobotController')

    implementation fileTree(dir: 'plugin', include: ['*.aar', '*.jar'])

    // Solvers Lib
    implementation "org.solverslib:core:0.3.4"
    implementation "org.solverslib:pedroPathing:0.3.4"
    implementation "org.solverslib:photon:0.3.4"

    // Pedro Pathing
    implementation 'com.pedropathing:ftc:2.1.0'
    implementation 'com.pedropathing:telemetry:1.0.0'

    // Panels Dashboard
    implementation "com.bylazar:fullpanels:1.0.12"

    // Test
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.14.2'
}

apply from: '../build.dependencies.gradle'